iimage: docker:latest
services:
  - docker:dind
before_script:
  - docker info
  - export
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin https://registry.pk-dev.com/v2/
  # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE"

  only:
    - tags
